In [12]:
"""
1.[1,100,2,5,6,7,8,9]의 리스트를 만들고 해당 리스트 아래와 같이 변경하시오.
"""
list = [1,100,2,5,6,7,8,9]
list.pop(1)
list.append(10)
print(list)

[1, 2, 5, 6, 7, 8, 9, 10]


In [21]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [22]:
import numpy as np

In [42]:
"""
2. 1번의 리스트를 배열로 만들어 아래와 같이 변경하시오
"""
arr = np.array(list)
arr = np.insert(arr, 2, [3,4])
arr = np.append(arr,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [43]:
'''
3. 2번의 배열에서 5보다 작거나 같은 값을 추출해 A라는 변수에 저장하고, 4보다 작거나 같은 값들을 B라는 변수에 저장하시오.
'''
A = arr[arr[:]>=5]
B = arr[arr[:] <=4]
print(A,"\n",B)

[ 5  6  7  8  9 10 11] 
 [1 2 3 4]


In [51]:
"""
4. AI 소프트웨어 학과 교수님 이름 5명과 사무실 전화번호 5개를 하나의 딕셔너리로 만드시오.
"""
AI = {"교수님 성함" : ["이태민 교수님","황득영 교수님","권세진 교수님","장영관 교수님","김창균 교수님"], "사무실 전화번호" : ["0335706378","0335706376","0335706377"
,"0335706585","0335706587"]}

print(AI["교수님 성함"])
print(AI["사무실 전화번호"])

['이태민 교수님', '황득영 교수님', '권세진 교수님', '장영관 교수님', '김창균 교수님']
['0335706378', '0335706376', '0335706377', '0335706585', '0335706587']


In [39]:
pip install pandas


   ---------------------------------------- 0.0/10.8 MB ? eta -:--:--
   ---------------------------------------  10.7/10.8 MB 61.3 MB/s eta 0:00:01
   ---------------------------------------- 10.8/10.8 MB 39.7 MB/s eta 0:00:00


In [40]:
import pandas as pd

In [59]:
'''
5. 4번 문제에서 생성한 딕셔너리를 데이터 프레임으로 저장하시오.
'''
df=pd.DataFrame(AI)
print(df)

    교수님 성함    사무실 전화번호
0  이태민 교수님  0335706378
1  황득영 교수님  0335706376
2  권세진 교수님  0335706377
3  장영관 교수님  0335706585
4  김창균 교수님  0335706587


In [61]:
'''
6 아래와 같이 text파일을 만들어서 이를 csv파일로 변경하여 저장하시오.
7. 해당 csv파일을 데이터 프레임으로 불러오시오.
'''

data1 = pd.read_csv("C:/Users/User/Desktop/새 폴더/Data1.csv")
print(data1)

       연령     학력  성과능력  성과태도
0  26~30세  대학원졸업     5     4
1  31세 이상  대학교졸업     4     3
2  31세 이상  전문대졸업     4     2
3  26~30세  대학원졸업     4     4
4  20~25세  대학교졸업     4     4
