In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [6]:
## 배열의 쉐입(차원, 크기)확인
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [18]:
A = "안녕하세요 지금은 데이터 전처리 수업 시간입니다."
str=A[:5] + A[5:10]
print(character)

안녕하세요 지금은 


In [19]:
수학 = 100
영어  = 60
합 = 수학 + 영어
print(("이번 시험에서 수학은 {}점 영어는 {}점 합은 {}점 맞았습니다.").format(수학, 영어,합))

이번 시험에서 수학은 100점 영어는 60점 합은 160점 맞았습니다.


In [20]:
print(("{:.2f}, {:.3f}").format(3.1415, 3.1415))

3.14, 3.142


In [32]:
url= " https://www.youtube.com/"
str = url.replace("https://","")
print(str)
str = "https://www.youtube.com/".replace("/","")
print(str)

 www.youtube.com/
https:www.youtube.com


In [38]:
A = [10,20,30,40,50,60,70,80,90]
A[0] + A[5]

70

In [62]:
a = ["독고영재, 50, 55", "김철수, 30"]
b = ["김철수,20","김영희, 25"]
print(a[0][:a[0].index(",")])

독고영재


In [63]:
a = ["hi", 10, "80", "김철수", 50,50.6]
print(f"리스트 전체 타입 : {type(a)}")
print(f"리스트 원소1 : {type(a[1])}")
print(f"리스트 원소2 : {type(a[3])}")
print(f"리스트 원소3 : {type(a[5])}")

리스트 전체 타입 : <class 'list'>
리스트 원소1 : <class 'int'>
리스트 원소2 : <class 'str'>
리스트 원소3 : <class 'float'>


In [70]:
a = ["hi", 10, "80", "김철수", 50,50.6]
a.append("종강")
a.append(1)
print(a)

['hi', 10, '80', '김철수', 50, 50.6, '종강', 1]


In [76]:
b = a[:]
b.pop(1)
print(b)
print(b.index(50))
b.pop(b.index(50))
print(b)

['hi', '80', '김철수', 50, 50.6, '종강', 1]
3
['hi', '80', '김철수', 50.6, '종강', 1]


In [84]:
a= np.array([1,2,3,4])
a= np.append(a,[4,5])## 말단 삽입
print(a)
a = np.insert(a, 1, [7,8])## 중간 삽입
print(a)
a = np.insert(a, 3, [10,11])## 중간 삽입
print(a)

[1 2 3 4 4 5]
[1 7 8 2 3 4 4 5]
[ 1  7  8 10 11  2  3  4  4  5]


In [89]:
a = np.array([1,2,3,4,5])
a = np.delete(a,[1,3])
a

array([1, 3, 5])

In [90]:
a1= a[a<=4]
print(a1)
a2 = a[a!=4]
print(a2)

[1 3]
[1 3 5]


In [92]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
merged_array = np.vstack((array1, array2))
print(merged_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [94]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
merged_array = np.hstack((array1, array2))
print(merged_array)

[[1 2 5 6]
 [3 4 7 8]]


In [101]:
A = {1:"김철수", 20: "박영희"}
print(A[1]) ## 없는 키 입력시 keyError
print(A.get(2))

김철수
None


In [ ]:
A = {"1":"김철수", 20: "박영희"}
print(A[1]) ## 없는 키 입력시 keyError
print(A.get(2))